### ISSUE TITLE
Add notes from meeting

### ISSUE THREAD

**Issue by ageorgou** [oracc/website#10]
It would be good for anyone that has notes (including @raquel-ucl and me) to put them on the wiki before we forget everything!

**Comment by sgrieve** [comment]
Agreed! I will type my notes up soon.

**Comment by raquel** [comment]
@ageorgou You had mentioned the wrong Raquel in your message

**Comment by ageorgou** [comment]
@raquel Oops, my apologies!

**Comment by raquel-ucl** [comment]
I've put my notes in the wiki:

https://github.com/oracc/website/wiki/ORACC-Server

I've also included parts of the notes you uploaded as well.

Please @ageorgou and @sgrieve review and feel free to correct things if you find anything that doesn't look right. Close this issue when it's ready.

**Comment by raquel-ucl** [comment]
@ageorgou and @sgrieve seem OK with the wiki compiling all our notes, so closing.
