### ISSUE TITLE
Open ports in oracc-build

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/website#12]
We'll need the following ports to be open by the sysadmins looking after oracc-build:

* ElasticSearch: 9200
* Flask: 5000
* Angular: 4200 and 4300

Note this ports are the default ones and it's easy to server the ES/Flask/Angular services in different ports if these are already being used. We have changed the configuration in iptables for these (or at least some of them), but we still suspect there is a firewall that is blocking access to them from the outside.

**Comment by raquel-ucl** [comment]
Steve mentioned in our last Skype meeting he contacted the IT team recently regarding the ports opening, and will let us know when he hears back.

**Comment by stinney** [comment]
My IT guys say "try now ..."

**Comment by ageorgou** [comment]
Ports 4200, 5000 and 9000 seem to be open (at least the Python SimpleHTTPServer works on them). Port 4300 seems closed.

**Comment by raquel-ucl** [comment]
Double confirm 4200 works, see http://build-oracc.museum.upenn.edu:4200.

**Comment by ageorgou** [comment]
4300 and 5100 are also open now, in addition to the above. This should be enough for production and staging versions of both the front- and back-end, and a version of ElasticSearch.
